<?php
// Database installation script
require_once 'config/config.php';

try {
    // Connect to MySQL server (without database)
    $pdo = new PDO("mysql:host=" . DB_HOST . ";charset=" . DB_CHARSET, DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "<h2>تثبيت قاعدة البيانات</h2>";
    
    // Read and execute schema
    $schema = file_get_contents('database/schema.sql');
    
    if ($schema === false) {
        throw new Exception('فشل في قراءة ملف قاعدة البيانات');
    }
    
    // Split SQL statements
    $statements = array_filter(array_map('trim', explode(';', $schema)));
    
    foreach ($statements as $statement) {
        if (!empty($statement)) {
            try {
                $pdo->exec($statement);
                echo "<p style='color: green;'>✓ تم تنفيذ: " . substr($statement, 0, 50) . "...</p>";
            } catch (PDOException $e) {
                echo "<p style='color: orange;'>⚠ تحذير: " . $e->getMessage() . "</p>";
            }
        }
    }
    
    echo "<h3 style='color: green;'>✅ تم تثبيت قاعدة البيانات بنجاح!</h3>";
    echo "<h4>بيانات الدخول الافتراضية:</h4>";
    echo "<ul>";
    echo "<li><strong>المدير العام:</strong> admin@expenses.com / admin123</li>";
    echo "</ul>";
    echo "<p><a href='login.php' style='background: #06B6D4; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>الذهاب لصفحة تسجيل الدخول</a></p>";
    
} catch (Exception $e) {
    echo "<h3 style='color: red;'>❌ خطأ في التثبيت:</h3>";
    echo "<p style='color: red;'>" . $e->getMessage() . "</p>";
    echo "<h4>تأكد من:</h4>";
    echo "<ul>";
    echo "<li>تشغيل خادم MySQL</li>";
    echo "<li>صحة بيانات الاتصال في config/database.php</li>";
    echo "<li>وجود صلاحيات إنشاء قواعد البيانات</li>";
    echo "</ul>";
}
?>

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تثبيت نظام إدارة المصروفات</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        h2, h3, h4 {
            color: #333;
        }
        p {
            margin: 10px 0;
        }
        ul {
            margin: 10px 0;
            padding-right: 20px;
        }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>
