<?php
// Reset admin password script
require_once 'config/config.php';
require_once 'config/database.php';

try {
    // Generate correct password hash for "admin123"
    $password = 'admin123';
    $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
    
    echo "<h2>إعادة تعيين كلمة مرور المدير</h2>";
    
    // Check if admin user exists
    $stmt = $pdo->prepare("SELECT id FROM users WHERE email = 'admin@expenses.com'");
    $stmt->execute();
    $admin = $stmt->fetch();
    
    if ($admin) {
        // Update existing admin password
        $stmt = $pdo->prepare("UPDATE users SET password = ? WHERE email = 'admin@expenses.com'");
        $stmt->execute([$hashedPassword]);
        echo "<p style='color: green;'>✅ تم تحديث كلمة مرور المدير بنجاح!</p>";
    } else {
        // Create new admin user
        $stmt = $pdo->prepare("INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, ?)");
        $stmt->execute(['Super Admin', 'admin@expenses.com', $hashedPassword, 'super_admin']);
        echo "<p style='color: green;'>✅ تم إنشاء حساب المدير بنجاح!</p>";
    }
    
    echo "<h4>بيانات الدخول:</h4>";
    echo "<ul>";
    echo "<li><strong>البريد الإلكتروني:</strong> admin@expenses.com</li>";
    echo "<li><strong>كلمة المرور:</strong> admin123</li>";
    echo "</ul>";
    
    echo "<p><a href='login.php' style='background: #06B6D4; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;'>تسجيل الدخول الآن</a></p>";
    
    // Test the password
    echo "<hr>";
    echo "<h4>اختبار كلمة المرور:</h4>";
    if (password_verify($password, $hashedPassword)) {
        echo "<p style='color: green;'>✅ كلمة المرور تعمل بشكل صحيح</p>";
    } else {
        echo "<p style='color: red;'>❌ خطأ في كلمة المرور</p>";
    }
    
} catch (Exception $e) {
    echo "<h3 style='color: red;'>❌ خطأ:</h3>";
    echo "<p style='color: red;'>" . $e->getMessage() . "</p>";
    
    echo "<h4>الحلول المقترحة:</h4>";
    echo "<ul>";
    echo "<li>تأكد من تشغيل MySQL في XAMPP</li>";
    echo "<li>تأكد من وجود قاعدة البيانات expenses_management</li>";
    echo "<li>شغل install.php أولاً</li>";
    echo "</ul>";
}
?>

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>إعادة تعيين كلمة مرور المدير</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        h2, h3, h4 {
            color: #333;
        }
        p {
            margin: 10px 0;
        }
        ul {
            margin: 10px 0;
            padding-right: 20px;
        }
        hr {
            margin: 20px 0;
            border: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <!-- Content is generated by PHP above -->
</body>
</html>
